### ISSUE TITLE
does not work within docker

### ISSUE THREAD

**Issue by u007** [janniks/basetag#13]
works properly on my development machine
but once deployed on docker, it states 
```
Error while running command start: Could not load function /usr/src/app/config/functions/cron.js: Cannot find module '$/util/logger'
```

**Comment by janniks** [comment]
Thanks for reporting! Can you share your Dockerfile?

**Comment by u007** [comment]
thank you:
Dockerfile
```
FROM node:12-alpine as main
ENV PORT "1337"
ENV NODE_ENV=production

WORKDIR /usr/src/app

ARG UID=app

RUN echo userid: $UID
RUN mkdir /.npm && chown $UID /.npm && chown $UID -R /usr/src/app
RUN mkdir /.config && chown $UID /.config

USER $UID

USER root

RUN chown $UID -R /usr/src/app

USER $UID

# RUN npm install
# RUN npm run build
# RUN cd /usr/src/app/tools && npm install


CMD ["npm", "run", "prod-start"]
```

docker-compose.yml
```
lthree_app:
    build:
      context: ./
      args:
        - UID=1001
    restart: unless-stopped
    volumes:
      - ./:/usr/src/app/
    environment:
      - NODE_ENV=production
```
